// @generated by neuradix-embedded-codegen 0.0.1. DO NOT EDIT.
//
// Source contract: io.neuradix.fixtures/legacy-probe@1.0.0
// Schema identity: sha256:27a575894cff9930868f7ec3c7a3ac8218b756eea36516b2b06e81f5c73445ef
// Wire: fixed little-endian, 45 bytes.
//
// Regenerate with:
//   neuradix contract generate <contract> --language nostd-rust --out-dir <dir>

/// Mixed-width scalar probe recorded by the pre-v2 codec
#[allow(dead_code)]
#[derive(Clone, Copy, Debug, PartialEq)]
pub struct LegacyProbe {
    /// rad
    pub yaw: f64,
    /// rad
    pub pitch: f64,
    /// count
    pub count: i32,
    /// armed
    pub armed: bool,
    /// Hz
    pub rate: f32,
    /// ticks
    pub ticks: u64,
    /// offset
    pub offset: i64,
    /// flags
    pub flags: u32,
}

#[allow(dead_code)]
impl LegacyProbe {
    /// The fixed wire length in bytes.
    pub const WIRE_LEN: usize = 45;
    /// Content-addressed schema identity.
    pub const SCHEMA_ID: &'static str =
        "sha256:27a575894cff9930868f7ec3c7a3ac8218b756eea36516b2b06e81f5c73445ef";

    /// Encode into `out` (little-endian). Returns the number of
    /// bytes written, or `None` if `out` is shorter than `WIRE_LEN`.
    pub fn encode(&self, out: &mut [u8]) -> Option<usize> {
        if out.len() < Self::WIRE_LEN {
            return None;
        }
        out[0..8].copy_from_slice(&self.yaw.to_le_bytes());
        out[8..16].copy_from_slice(&self.pitch.to_le_bytes());
        out[16..20].copy_from_slice(&self.count.to_le_bytes());
        out[20] = self.armed as u8;
        out[21..25].copy_from_slice(&self.rate.to_le_bytes());
        out[25..33].copy_from_slice(&self.ticks.to_le_bytes());
        out[33..41].copy_from_slice(&self.offset.to_le_bytes());
        out[41..45].copy_from_slice(&self.flags.to_le_bytes());
        Some(Self::WIRE_LEN)
    }

    /// Decode from little-endian `input`. Returns `None` if
    /// `input` is shorter than `WIRE_LEN`.
    pub fn decode(input: &[u8]) -> Option<Self> {
        if input.len() < Self::WIRE_LEN {
            return None;
        }
        Some(Self {
            yaw: f64::from_le_bytes(input[0..8].try_into().ok()?),
            pitch: f64::from_le_bytes(input[8..16].try_into().ok()?),
            count: i32::from_le_bytes(input[16..20].try_into().ok()?),
            armed: input[20] != 0,
            rate: f32::from_le_bytes(input[21..25].try_into().ok()?),
            ticks: u64::from_le_bytes(input[25..33].try_into().ok()?),
            offset: i64::from_le_bytes(input[33..41].try_into().ok()?),
            flags: u32::from_le_bytes(input[41..45].try_into().ok()?),
        })
    }
}
