//! Deterministic Rust code generation from a validated contract.
//!
//! This is the first, deliberately narrow Rust projection. It supports exactly
//! the constructs the contract model supports today: a `StreamContract` whose
//! payload is an object of scalar primitive fields. Anything outside that subset
//! is rejected with a clear [`ContractError::Unsupported`] error rather than
//! silently producing incorrect code.
//!
//! The output is emitted already formatted to `rustfmt` defaults so that
//! generated files pass `cargo fmt --check`, and it is a pure function of the
//! validated [`Contract`], so it is byte-for-byte reproducible and can be
//! golden-file tested.

use std::fmt::Write as _;

use crate::canonical::schema_identity;
use crate::error::{ContractError, Result};
use crate::model::Contract;

/// The version of the generator, embedded in generated files for traceability.
pub const GENERATOR_VERSION: &str = env!("CARGO_PKG_VERSION");

/// A generated Rust module.
#[derive(Debug, Clone)]
pub struct GeneratedRust {
    /// The `snake_case` module/file stem, e.g. `vehicle_depth`.
    pub module_name: String,
    /// The `PascalCase` type name, e.g. `VehicleDepth`.
    pub type_name: String,
    /// The formatted Rust source, ending in a single newline.
    pub code: String,
}

/// Generate the Rust projection for a contract.
pub fn generate_rust(contract: &Contract) -> Result<GeneratedRust> {
    // The model only ever holds a supported kind today, but guard explicitly so
    // that adding kinds later cannot silently produce wrong output.
    let module_name = to_snake_case(&contract.metadata.name);
    let type_name = to_pascal_case(&contract.metadata.name);
    if type_name.is_empty() {
        return Err(ContractError::Unsupported {
            name: contract.identifier(),
            reason: format!(
                "cannot derive a Rust type name from `{}`",
                contract.metadata.name
            ),
        });
    }

    let schema_id = schema_identity(contract);
    let all_copy = contract.spec.payload.fields.iter().all(|f| f.ty.is_copy());

    let mut derives = vec!["Clone"];
    if all_copy {
        derives.push("Copy");
    }
    derives.push("Debug");
    derives.push("PartialEq");

    let mut code = String::new();

    // Header: inner attribute first (rustfmt keeps it at the top), then banner.
    code.push_str("#![allow(dead_code)]\n");
    code.push('\n');
    let _ = writeln!(
        code,
        "// @generated by neuradix-contracts {GENERATOR_VERSION}. DO NOT EDIT."
    );
    code.push_str("//\n");
    let _ = writeln!(
        code,
        "// Source contract: {}/{}@{}",
        contract.metadata.namespace, contract.metadata.name, contract.metadata.version
    );
    let _ = writeln!(code, "// Schema identity: {schema_id}");
    code.push_str("//\n");
    code.push_str("// Regenerate with:\n");
    code.push_str("//   neuradix contract generate <contract> --language rust --out-dir <dir>\n");
    code.push('\n');

    // Type doc from the contract description, if any.
    if let Some(desc) = &contract.spec.description {
        for line in desc.lines() {
            let _ = writeln!(code, "/// {line}");
        }
    }
    let _ = writeln!(code, "#[derive({})]", derives.join(", "));
    let _ = writeln!(code, "pub struct {type_name} {{");
    for field in &contract.spec.payload.fields {
        match &field.unit {
            Some(unit) => {
                let _ = writeln!(code, "    /// unit: {unit}");
            }
            None => {
                let _ = writeln!(code, "    /// {}", field.name);
            }
        }
        let _ = writeln!(code, "    pub {}: {},", field.name, field.ty.rust_type());
    }
    code.push_str("}\n\n");

    // Associated metadata constants.
    let _ = writeln!(code, "impl {type_name} {{");
    code.push_str("    /// Contract namespace.\n");
    emit_str_const(&mut code, "NAMESPACE", &contract.metadata.namespace);
    code.push_str("    /// Contract name.\n");
    emit_str_const(&mut code, "NAME", &contract.metadata.name);
    code.push_str("    /// Contract semantic version.\n");
    emit_str_const(&mut code, "VERSION", &contract.metadata.version.to_string());
    code.push_str("    /// Content-addressed schema identity.\n");
    emit_str_const(&mut code, "SCHEMA_ID", schema_id.as_str());
    code.push_str("}\n");

    Ok(GeneratedRust {
        module_name,
        type_name,
        code,
    })
}

/// Emit a `pub const NAME: &'static str = "value";` inside an `impl` block,
/// matching `rustfmt` (max_width = 100): if the single-line form would exceed
/// 100 columns, the initializer is wrapped onto the next line indented by 8.
fn emit_str_const(code: &mut String, name: &str, value: &str) {
    let single = format!("    pub const {name}: &'static str = \"{value}\";");
    if single.len() <= 100 {
        code.push_str(&single);
        code.push('\n');
    } else {
        let _ = writeln!(code, "    pub const {name}: &'static str =");
        let _ = writeln!(code, "        \"{value}\";");
    }
}

/// Convert a contract name such as `vehicle-depth` to `vehicle_depth`.
fn to_snake_case(name: &str) -> String {
    name.chars()
        .map(|c| {
            if c == '-' || c == ' ' {
                '_'
            } else {
                c.to_ascii_lowercase()
            }
        })
        .collect()
}

/// Convert a contract name such as `vehicle-depth` to `VehicleDepth`.
fn to_pascal_case(name: &str) -> String {
    name.split(['-', '_', ' '])
        .filter(|segment| !segment.is_empty())
        .map(|segment| {
            let mut chars = segment.chars();
            match chars.next() {
                Some(first) => {
                    let mut out = first.to_ascii_uppercase().to_string();
                    out.extend(chars.map(|c| c.to_ascii_lowercase()));
                    out
                }
                None => String::new(),
            }
        })
        .collect()
}
