// @generated by neuradix-embedded-codegen 0.0.1. DO NOT EDIT.
// Source contract: io.neuradix.navigation/vehicle-depth@1.0.0
// Schema identity: sha256:4c9c5d9381658f7779ef0d3ef11eda3f29006f7e751d06dba40a12d6f4ce2a73
// Codec: neuradix.scalar-le.v2
// Wire identity: sha256:4780f56bd7e4780987152907da8156c19dd2946470bc550c35abb16285d7b11d
// C++ target: portable
// Wire: fixed little-endian, 16 bytes.
#pragma once
#include <stdint.h>
#include <stddef.h>
#include <string.h>
#include <limits.h>
#include <float.h>

static_assert(CHAR_BIT == 8, "Neuradix requires 8-bit bytes");
static_assert(sizeof(double) == 8 && FLT_RADIX == 2 && DBL_MANT_DIG == 53 && DBL_MAX_EXP == 1024, "Neuradix float64 requires IEEE-754 binary64; unsupported target ABI");
#if defined(__FLOAT_WORD_ORDER__) && defined(__BYTE_ORDER__)
static_assert(__FLOAT_WORD_ORDER__ == __BYTE_ORDER__, "Neuradix requires matching float and integer byte order");
#endif

namespace neuradix {

struct VehicleDepth {
  double depth;
  double uncertainty;

  static constexpr size_t WIRE_LEN = 16;
  static constexpr const char* SCHEMA_ID = "sha256:4c9c5d9381658f7779ef0d3ef11eda3f29006f7e751d06dba40a12d6f4ce2a73";
  static constexpr const char* CODEC_ID = "neuradix.scalar-le.v2";
  static constexpr const char* WIRE_ID = "sha256:4780f56bd7e4780987152907da8156c19dd2946470bc550c35abb16285d7b11d";

  // Encode into `out` (>= WIRE_LEN); returns bytes written, 0 if too small.
  size_t encode(uint8_t* out, size_t cap) const {
    if (out == nullptr || cap < WIRE_LEN) return 0;
    {
      uint64_t b;
      memcpy(&b, &this->depth, sizeof(this->depth));
      for (size_t k = 0; k < 8; ++k) out[0 + k] = (uint8_t)(b >> (8 * k));
    }
    {
      uint64_t b;
      memcpy(&b, &this->uncertainty, sizeof(this->uncertainty));
      for (size_t k = 0; k < 8; ++k) out[8 + k] = (uint8_t)(b >> (8 * k));
    }
    return WIRE_LEN;
  }

  // Require the sender's bound identity and exact payload length.
  // Returns false on invalid input; leaves out unchanged on failure.
  static bool decode(const uint8_t* in, size_t len, VehicleDepth& out, const char* peer_wire_id) {
    if (in == nullptr || peer_wire_id == nullptr || len != WIRE_LEN || strcmp(peer_wire_id, WIRE_ID) != 0) return false;
    {
      uint64_t b = 0;
      for (size_t k = 0; k < 8; ++k) b |= (uint64_t)in[0 + k] << (8 * k);
      memcpy(&out.depth, &b, sizeof(out.depth));
    }
    {
      uint64_t b = 0;
      for (size_t k = 0; k < 8; ++k) b |= (uint64_t)in[8 + k] << (8 * k);
      memcpy(&out.uncertainty, &b, sizeof(out.uncertainty));
    }
    return true;
  }
};

}  // namespace neuradix
