// @generated by neuradix-embedded-codegen 0.0.1. DO NOT EDIT.
// Source contract: io.neuradix.navigation/vehicle-depth@1.0.0
// Schema identity: sha256:4c9c5d9381658f7779ef0d3ef11eda3f29006f7e751d06dba40a12d6f4ce2a73
// Wire: fixed little-endian, 16 bytes.
#pragma once
#include <cstdint>
#include <cstddef>
#include <cstring>

namespace neuradix {

struct VehicleDepth {
  double depth;
  double uncertainty;

  static constexpr size_t WIRE_LEN = 16;

  // Encode into `out` (>= WIRE_LEN); returns bytes written, 0 if too small.
  size_t encode(uint8_t* out, size_t cap) const {
    if (cap < WIRE_LEN) return 0;
    {
      uint64_t b;
      memcpy(&b, &this->depth, 8);
      for (size_t k = 0; k < 8; ++k) out[0 + k] = (uint8_t)(b >> (8 * k));
    }
    {
      uint64_t b;
      memcpy(&b, &this->uncertainty, 8);
      for (size_t k = 0; k < 8; ++k) out[8 + k] = (uint8_t)(b >> (8 * k));
    }
    return WIRE_LEN;
  }

  // Decode from `in` (>= WIRE_LEN); returns false if too small.
  static bool decode(const uint8_t* in, size_t len, VehicleDepth& out) {
    if (len < WIRE_LEN) return false;
    {
      uint64_t b = 0;
      for (size_t k = 0; k < 8; ++k) b |= (uint64_t)in[0 + k] << (8 * k);
      memcpy(&out.depth, &b, 8);
    }
    {
      uint64_t b = 0;
      for (size_t k = 0; k < 8; ++k) b |= (uint64_t)in[8 + k] << (8 * k);
      memcpy(&out.uncertainty, &b, 8);
    }
    return true;
  }
};

}  // namespace neuradix
