// @generated by neuradix-embedded-codegen 0.0.1. DO NOT EDIT.
//
// Source contract: io.neuradix.navigation/vehicle-depth@1.0.0
// Schema identity: sha256:4c9c5d9381658f7779ef0d3ef11eda3f29006f7e751d06dba40a12d6f4ce2a73
// Wire: fixed little-endian, 16 bytes.
//
// Regenerate with:
//   neuradix contract generate <contract> --language nostd-rust --out-dir <dir>

/// Vehicle depth below the configured water reference
#[allow(dead_code)]
#[derive(Clone, Copy, Debug, PartialEq)]
pub struct VehicleDepth {
    /// m
    pub depth: f64,
    /// m
    pub uncertainty: f64,
}

#[allow(dead_code)]
impl VehicleDepth {
    /// The fixed wire length in bytes.
    pub const WIRE_LEN: usize = 16;
    /// Content-addressed schema identity.
    pub const SCHEMA_ID: &'static str =
        "sha256:4c9c5d9381658f7779ef0d3ef11eda3f29006f7e751d06dba40a12d6f4ce2a73";

    /// Encode into `out` (little-endian). Returns the number of
    /// bytes written, or `None` if `out` is shorter than `WIRE_LEN`.
    pub fn encode(&self, out: &mut [u8]) -> Option<usize> {
        if out.len() < Self::WIRE_LEN {
            return None;
        }
        out[0..8].copy_from_slice(&self.depth.to_le_bytes());
        out[8..16].copy_from_slice(&self.uncertainty.to_le_bytes());
        Some(Self::WIRE_LEN)
    }

    /// Decode from little-endian `input`. Returns `None` if
    /// `input` is shorter than `WIRE_LEN`.
    pub fn decode(input: &[u8]) -> Option<Self> {
        if input.len() < Self::WIRE_LEN {
            return None;
        }
        Some(Self {
            depth: f64::from_le_bytes(input[0..8].try_into().ok()?),
            uncertainty: f64::from_le_bytes(input[8..16].try_into().ok()?),
        })
    }
}
