//! Board channel table generated from a verified channel manifest.
//!
//! The emitted constants feed `neuradix_embedded_transport::ChannelTable::new`,
//! which recomputes the manifest digest from the bindings and refuses a
//! mismatch. Generating both from one verified [`ChannelManifest`] removes
//! hand-copied bindings; editing either constant makes table construction fail.

use std::fmt::Write as _;

use neuradix_contracts::ChannelManifest;

use crate::rust_gen::GENERATOR_VERSION;

/// Rust source defining `MANIFEST_DIGEST: [u8; 32]` and
/// `CHANNELS: [ChannelBinding; N]` (entries in compact-ID order). The source
/// names `neuradix_embedded_transport::ChannelBinding` and needs no allocator.
pub fn generate_channel_table(manifest: &ChannelManifest) -> String {
    let mut out = String::new();
    let _ = writeln!(
        out,
        "// @generated by neuradix-embedded-codegen {GENERATOR_VERSION}. DO NOT EDIT.\n\
         //\n\
         // Channel manifest: {}\n\
         // Digest: {}\n\
         //\n\
         // Build the board table with\n\
         //   ChannelTable::<N>::new(MANIFEST_DIGEST, &CHANNELS)\n\
         // which recomputes the digest from CHANNELS and rejects any mismatch.\n",
        neuradix_contracts::channel::CHANNEL_MANIFEST_VERSION,
        manifest.digest(),
    );
    let _ = writeln!(out, "/// Digest of the verified channel manifest.");
    let _ = writeln!(out, "#[allow(dead_code)]");
    let _ = writeln!(out, "pub const MANIFEST_DIGEST: [u8; 32] = [");
    for row in manifest.digest_bytes().chunks(8) {
        let bytes: Vec<String> = row.iter().map(|b| format!("0x{b:02x}")).collect();
        let _ = writeln!(out, "    {},", bytes.join(", "));
    }
    let _ = writeln!(out, "];\n");
    let channels = manifest.channels();
    let _ = writeln!(out, "/// Manifest entries in ascending compact-ID order.");
    let _ = writeln!(out, "#[allow(dead_code)]");
    let _ = writeln!(
        out,
        "pub const CHANNELS: [neuradix_embedded_transport::ChannelBinding; {}] = [",
        channels.len()
    );
    for c in channels {
        // `{:?}` of a `str` is a valid Rust string literal.
        let _ = writeln!(
            out,
            "    neuradix_embedded_transport::ChannelBinding {{\n        \
             compact_id: {},\n        wire_len: {},\n        name: {:?},\n        \
             codec_id: {:?},\n        schema_id: {:?},\n        wire_id: {:?},\n    }},",
            c.compact_id, c.wire_len, c.name, c.codec_id, c.schema_id, c.wire_id
        );
    }
    let _ = writeln!(out, "];");
    out
}
