//! Arduino/C++ projection: a header with the payload struct and fixed
//! little-endian encode/decode, byte-exact with the Rust projections.

use std::fmt::Write as _;

use neuradix_contracts::{Contract, PrimitiveType, schema_identity};

use crate::error::CodegenError;
use crate::golden::GoldenSet;
use crate::names::{to_pascal_case, to_snake_case};
use crate::rust_gen::GENERATOR_VERSION;
use crate::wire::field_size;

/// A generated C++ header.
#[derive(Debug, Clone)]
pub struct GeneratedCpp {
    /// The header file stem (e.g. `vehicle_depth`).
    pub header_name: String,
    /// The C++ type name.
    pub type_name: String,
    /// The header source.
    pub code: String,
}

fn cpp_type(ty: PrimitiveType) -> &'static str {
    match ty {
        PrimitiveType::Float64 => "double",
        PrimitiveType::Float32 => "float",
        PrimitiveType::Int32 => "int32_t",
        PrimitiveType::Int64 => "int64_t",
        PrimitiveType::Uint32 => "uint32_t",
        PrimitiveType::Uint64 => "uint64_t",
        PrimitiveType::Bool => "bool",
        PrimitiveType::Str => "/*unsupported*/",
    }
}

fn uint_type(size: usize) -> &'static str {
    match size {
        8 => "uint64_t",
        4 => "uint32_t",
        _ => "uint8_t",
    }
}

/// Generate the C++ header projection of a contract.
pub fn generate_cpp(contract: &Contract) -> Result<GeneratedCpp, CodegenError> {
    let type_name = to_pascal_case(&contract.metadata.name);
    if type_name.is_empty() {
        return Err(CodegenError::BadName(contract.identifier()));
    }
    let header_name = to_snake_case(&contract.metadata.name);
    let schema_id = schema_identity(contract);

    let mut offsets = Vec::new();
    let mut offset = 0usize;
    for field in &contract.spec.payload.fields {
        let size = field_size(field.ty, &field.name)?;
        offsets.push((offset, size));
        offset += size;
    }
    let wire_len = offset;

    let mut code = String::new();
    let _ = writeln!(
        code,
        "// @generated by neuradix-embedded-codegen {GENERATOR_VERSION}. DO NOT EDIT."
    );
    let _ = writeln!(
        code,
        "// Source contract: {}/{}@{}",
        contract.metadata.namespace, contract.metadata.name, contract.metadata.version
    );
    let _ = writeln!(code, "// Schema identity: {schema_id}");
    let _ = writeln!(code, "// Wire: fixed little-endian, {wire_len} bytes.");
    code.push_str("#pragma once\n");
    code.push_str("#include <cstdint>\n#include <cstddef>\n#include <cstring>\n\n");
    code.push_str("namespace neuradix {\n\n");
    let _ = writeln!(code, "struct {type_name} {{");
    for field in &contract.spec.payload.fields {
        let _ = writeln!(code, "  {} {};", cpp_type(field.ty), field.name);
    }
    code.push('\n');
    let _ = writeln!(code, "  static constexpr size_t WIRE_LEN = {wire_len};");
    code.push('\n');

    // encode
    code.push_str("  // Encode into `out` (>= WIRE_LEN); returns bytes written, 0 if too small.\n");
    code.push_str("  size_t encode(uint8_t* out, size_t cap) const {\n");
    code.push_str("    if (cap < WIRE_LEN) return 0;\n");
    for (field, (off, size)) in contract.spec.payload.fields.iter().zip(&offsets) {
        emit_cpp_encode_field(&mut code, &field.name, field.ty, *off, *size);
    }
    let _ = writeln!(code, "    return WIRE_LEN;\n  }}");
    code.push('\n');

    // decode
    code.push_str("  // Decode from `in` (>= WIRE_LEN); returns false if too small.\n");
    let _ = writeln!(
        code,
        "  static bool decode(const uint8_t* in, size_t len, {type_name}& out) {{"
    );
    code.push_str("    if (len < WIRE_LEN) return false;\n");
    for (field, (off, size)) in contract.spec.payload.fields.iter().zip(&offsets) {
        emit_cpp_decode_field(&mut code, &field.name, field.ty, *off, *size);
    }
    code.push_str("    return true;\n  }\n");

    code.push_str("};\n\n");
    code.push_str("}  // namespace neuradix\n");

    Ok(GeneratedCpp {
        header_name,
        type_name,
        code,
    })
}

fn emit_cpp_encode_field(
    code: &mut String,
    name: &str,
    ty: PrimitiveType,
    off: usize,
    size: usize,
) {
    if ty == PrimitiveType::Bool {
        let _ = writeln!(code, "    out[{off}] = this->{name} ? 1 : 0;");
        return;
    }
    let ut = uint_type(size);
    let _ = writeln!(code, "    {{");
    let _ = writeln!(code, "      {ut} b;");
    if matches!(ty, PrimitiveType::Float64 | PrimitiveType::Float32) {
        let _ = writeln!(code, "      memcpy(&b, &this->{name}, {size});");
    } else {
        let _ = writeln!(code, "      b = ({ut})this->{name};");
    }
    let _ = writeln!(
        code,
        "      for (size_t k = 0; k < {size}; ++k) out[{off} + k] = (uint8_t)(b >> (8 * k));"
    );
    let _ = writeln!(code, "    }}");
}

fn emit_cpp_decode_field(
    code: &mut String,
    name: &str,
    ty: PrimitiveType,
    off: usize,
    size: usize,
) {
    if ty == PrimitiveType::Bool {
        let _ = writeln!(code, "    out.{name} = in[{off}] != 0;");
        return;
    }
    let ut = uint_type(size);
    let _ = writeln!(code, "    {{");
    let _ = writeln!(code, "      {ut} b = 0;");
    let _ = writeln!(
        code,
        "      for (size_t k = 0; k < {size}; ++k) b |= ({ut})in[{off} + k] << (8 * k);"
    );
    if matches!(ty, PrimitiveType::Float64 | PrimitiveType::Float32) {
        let _ = writeln!(code, "      memcpy(&out.{name}, &b, {size});");
    } else {
        let _ = writeln!(code, "      out.{name} = ({})b;", cpp_type(ty));
    }
    let _ = writeln!(code, "    }}");
}

/// Generate a self-checking C++ `main()` that verifies every golden vector: it
/// encodes the baked values and compares to the expected bytes, and decodes the
/// expected bytes and re-encodes to check the round trip. Exits non-zero on any
/// mismatch. Compiling and running this proves the C++ projection agrees with
/// the Rust reference on the wire.
pub fn cpp_conformance_main(
    contract: &Contract,
    golden: &GoldenSet,
) -> Result<String, CodegenError> {
    let type_name = to_pascal_case(&contract.metadata.name);
    let header = to_snake_case(&contract.metadata.name);
    let rows = GoldenSet::value_rows(contract)?;

    let mut code = String::new();
    let _ = writeln!(code, "#include \"{header}.h\"");
    code.push_str("#include <cstdio>\n#include <cstring>\n\n");
    code.push_str("int main() {\n  int failures = 0;\n");

    for ((vname, values), vector) in rows.iter().zip(&golden.vectors) {
        let fields = &contract.spec.payload.fields;
        let expected = hex_to_cpp_array(&vector.bytes_hex);
        let _ = writeln!(code, "  {{");
        let _ = writeln!(code, "    neuradix::{type_name} v;");
        for (field, value) in fields.iter().zip(values) {
            let _ = writeln!(code, "    v.{} = {};", field.name, value.cpp_literal());
        }
        let _ = writeln!(code, "    const uint8_t expected[] = {{{expected}}};");
        let _ = writeln!(code, "    uint8_t buf[neuradix::{type_name}::WIRE_LEN];");
        let _ = writeln!(code, "    size_t n = v.encode(buf, sizeof(buf));");
        let _ = writeln!(
            code,
            "    if (n != sizeof(expected) || memcmp(buf, expected, sizeof(expected)) != 0) {{ printf(\"FAIL encode {vname}\\n\"); failures++; }}"
        );
        // decode expected, re-encode, check round trip.
        let _ = writeln!(code, "    neuradix::{type_name} d;");
        let _ = writeln!(code, "    uint8_t buf2[neuradix::{type_name}::WIRE_LEN];");
        let _ = writeln!(
            code,
            "    if (!neuradix::{type_name}::decode(expected, sizeof(expected), d) || d.encode(buf2, sizeof(buf2)) != sizeof(expected) || memcmp(buf2, expected, sizeof(expected)) != 0) {{ printf(\"FAIL roundtrip {vname}\\n\"); failures++; }}"
        );
        let _ = writeln!(code, "  }}");
    }

    code.push_str("  if (failures == 0) printf(\"ALL_PASS\\n\");\n");
    code.push_str("  return failures;\n}\n");
    Ok(code)
}

fn hex_to_cpp_array(hex: &str) -> String {
    let bytes: Vec<String> = hex
        .as_bytes()
        .chunks(2)
        .map(|pair| {
            let s = core::str::from_utf8(pair).unwrap_or("00");
            format!("0x{s}")
        })
        .collect();
    bytes.join(", ")
}
