//! `no_std` Rust projection: a payload struct with fixed little-endian
//! encode/decode, usable directly on an MCU.

use std::fmt::Write as _;

use neuradix_contracts::{Contract, PrimitiveType, schema_identity};

use crate::error::CodegenError;
use crate::layout::{WireLayout, canonical_fields};
use crate::names::{to_pascal_case, to_snake_case};

/// The generator version, embedded for traceability.
pub const GENERATOR_VERSION: &str = env!("CARGO_PKG_VERSION");

/// A generated `no_std` Rust module.
#[derive(Debug, Clone)]
pub struct GeneratedRust {
    /// The `snake_case` module/file stem.
    pub module_name: String,
    /// The `PascalCase` type name.
    pub type_name: String,
    /// The formatted, `rustfmt`-clean source, ending in a newline.
    pub code: String,
}

/// Generate the `no_std` Rust projection of a contract.
pub fn generate_nostd_rust(contract: &Contract) -> Result<GeneratedRust, CodegenError> {
    let type_name = to_pascal_case(&contract.metadata.name);
    if type_name.is_empty() {
        return Err(CodegenError::BadName(contract.identifier()));
    }
    let module_name = to_snake_case(&contract.metadata.name);
    let schema_id = schema_identity(contract);

    let layout = WireLayout::for_contract(contract)?;
    let fields = canonical_fields(contract);
    let wire_len = layout.wire_len;

    let mut code = String::new();
    let _ = writeln!(
        code,
        "// @generated by neuradix-embedded-codegen {GENERATOR_VERSION}. DO NOT EDIT."
    );
    code.push_str("//\n");
    let _ = writeln!(
        code,
        "// Source contract: {}/{}@{}",
        contract.metadata.namespace, contract.metadata.name, contract.metadata.version
    );
    let _ = writeln!(code, "// Schema identity: {schema_id}");
    let _ = writeln!(code, "// Codec: {}", layout.codec_id);
    let _ = writeln!(code, "// Wire identity: {}", layout.wire_id);
    let _ = writeln!(code, "// Wire: fixed little-endian, {wire_len} bytes.");
    code.push_str("//\n");
    code.push_str("// Regenerate with:\n");
    code.push_str(
        "//   neuradix contract generate <contract> --language nostd-rust --out-dir <dir>\n\n",
    );

    if let Some(desc) = &contract.spec.description {
        for line in desc.lines() {
            let _ = writeln!(code, "/// {line}");
        }
    }
    code.push_str("#[allow(dead_code)]\n");
    code.push_str("#[derive(Clone, Copy, Debug, PartialEq)]\n");
    let _ = writeln!(code, "pub struct {type_name} {{");
    for field in &fields {
        let _ = writeln!(
            code,
            "    /// {}",
            field.unit.clone().unwrap_or_else(|| field.name.clone())
        );
        let _ = writeln!(code, "    pub {}: {},", field.name, field.ty.rust_type());
    }
    code.push_str("}\n\n");

    code.push_str("#[allow(dead_code)]\n");
    let _ = writeln!(code, "impl {type_name} {{");
    let _ = writeln!(code, "    /// The fixed wire length in bytes.");
    let _ = writeln!(code, "    pub const WIRE_LEN: usize = {wire_len};");
    let _ = writeln!(code, "    /// Content-addressed schema identity.");
    emit_str_const(&mut code, "SCHEMA_ID", schema_id.as_str());
    code.push_str("    /// Versioned scalar codec.\n");
    emit_str_const(&mut code, "CODEC_ID", &layout.codec_id);
    code.push_str("    /// Full wire binding identity; compare with the sender's manifest.\n");
    emit_str_const(&mut code, "WIRE_ID", &layout.wire_id);
    code.push('\n');

    // encode
    code.push_str("    /// Encode into `out` (little-endian). Returns the number of\n");
    code.push_str("    /// bytes written, or `None` if `out` is shorter than `WIRE_LEN`.\n");
    code.push_str("    pub fn encode(&self, out: &mut [u8]) -> Option<usize> {\n");
    code.push_str("        if out.len() < Self::WIRE_LEN {\n            return None;\n        }\n");
    for (field, wire) in fields.iter().zip(&layout.fields) {
        let (off, size) = (wire.offset, wire.size);
        if field.ty == PrimitiveType::Bool {
            let _ = writeln!(code, "        out[{off}] = self.{} as u8;", field.name);
        } else {
            let _ = writeln!(
                code,
                "        out[{off}..{}].copy_from_slice(&self.{}.to_le_bytes());",
                off + size,
                field.name
            );
        }
    }
    code.push_str("        Some(Self::WIRE_LEN)\n    }\n\n");

    // decode
    code.push_str("    /// Decode an exact payload using the sender's bound wire identity.\n");
    code.push_str("    /// Rejects identity/length mismatches and non-canonical booleans.\n");
    code.push_str("    pub fn decode(input: &[u8], peer_wire_id: &str) -> Option<Self> {\n");
    code.push_str(
        "        if peer_wire_id != Self::WIRE_ID || input.len() != Self::WIRE_LEN {\n            return None;\n        }\n",
    );
    for (field, wire) in fields.iter().zip(&layout.fields) {
        if field.ty == PrimitiveType::Bool {
            let _ = writeln!(code, "        if input[{}] > 1 {{", wire.offset);
            code.push_str("            return None;\n        }\n");
        }
    }
    code.push_str("        Some(Self {\n");
    for (field, wire) in fields.iter().zip(&layout.fields) {
        let (off, size) = (wire.offset, wire.size);
        if field.ty == PrimitiveType::Bool {
            let _ = writeln!(code, "            {}: input[{off}] != 0,", field.name);
        } else {
            let _ = writeln!(
                code,
                "            {}: {}::from_le_bytes(input[{off}..{}].try_into().ok()?),",
                field.name,
                field.ty.rust_type(),
                off + size
            );
        }
    }
    code.push_str("        })\n    }\n");
    code.push_str("}\n");

    Ok(GeneratedRust {
        module_name,
        type_name,
        code,
    })
}

/// Emit a `pub const NAME: &'static str = "value";` inside an `impl`, wrapping
/// the initializer onto the next line (indent 8) when the single-line form would
/// exceed `rustfmt`'s 100-column width — so generated files pass `cargo fmt`.
fn emit_str_const(code: &mut String, name: &str, value: &str) {
    let single = format!("    pub const {name}: &'static str = \"{value}\";");
    if single.len() <= 100 {
        code.push_str(&single);
        code.push('\n');
    } else {
        let _ = writeln!(code, "    pub const {name}: &'static str =");
        let _ = writeln!(code, "        \"{value}\";");
    }
}
