#![allow(dead_code)]

// @generated by neuradix-contracts 0.0.1. DO NOT EDIT.
//
// Source contract: io.neuradix.navigation/vehicle-depth@1.0.0
// Schema identity: sha256:4c9c5d9381658f7779ef0d3ef11eda3f29006f7e751d06dba40a12d6f4ce2a73
//
// Regenerate with:
//   neuradix contract generate <contract> --language rust --out-dir <dir>

/// Vehicle depth below the configured water reference
#[derive(Clone, Copy, Debug, PartialEq)]
pub struct VehicleDepth {
    /// unit: m
    pub depth: f64,
    /// unit: m
    pub uncertainty: f64,
}

impl VehicleDepth {
    /// Contract namespace.
    pub const NAMESPACE: &'static str = "io.neuradix.navigation";
    /// Contract name.
    pub const NAME: &'static str = "vehicle-depth";
    /// Contract semantic version.
    pub const VERSION: &'static str = "1.0.0";
    /// Content-addressed schema identity.
    pub const SCHEMA_ID: &'static str =
        "sha256:4c9c5d9381658f7779ef0d3ef11eda3f29006f7e751d06dba40a12d6f4ce2a73";
}
